sudo: false
language: cpp
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.7
      addons: {apt: {packages: [g++-4.7], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-4.8
      addons: {apt: {packages: [g++-4.8], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-4.9
      addons: {apt: {packages: [g++-4.9], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-5
      addons: {apt: {packages: [g++-5], sources: [ubuntu-toolchain-r-test]}}
    - compiler: clang
      env: COMPILER=clang++
      addons: {apt: {packages: [g++-4.7], sources: [ubuntu-toolchain-r-test]}}
    - compiler: clang
      env: COMPILER=clang++-3.5
      addons: {apt: {packages: [clang-3.5], sources: [ubuntu-toolchain-r-test,llvm-toolchain-precise-3.5]}}
    - compiler: clang
      env: COMPILER=clang++-3.6
      addons: {apt: {packages: [clang-3.6], sources: [ubuntu-toolchain-r-test,llvm-toolchain-precise-3.6]}}
script:
  - CXX=$COMPILER make -C src full
