dist: trusty
sudo: false
language: cpp
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.7
      addons: {apt: {packages: [g++-4.7], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-4.8
      addons: {apt: {packages: [g++-4.8], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-4.9
      addons: {apt: {packages: [g++-4.9], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-5
      addons: {apt: {packages: [g++-5], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-6
      addons: {apt: {packages: [g++-6], sources: [ubuntu-toolchain-r-test]}}
    - compiler: clang
      env: COMPILER=clang++
script:
  - if test "$COMPILER" = "g++-4.7"; then COMPILER="g++-4.7 -D_GLIBCXX_USE_NANOSLEEP"; fi
  - CXX=$COMPILER C_FLAGS=-Werror make -k -C src full
  - CXX=$COMPILER C_FLAGS=-Werror make -k -C tests parsito_bundle
  - perl tests/ascii_only.pl
